wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.5
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711809707.0
    t:
      1:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 103
      3:
      - 7
      - 19
      - 23
      4: 3.9.13
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss_step
      5: 1
      6:
      - 1
    - 1: valid_acc_step
      5: 1
      6:
      - 1
    - 1: val_loss_epoch
      5: 1
      6:
      - 1
    - 1: valid_acc_epoch
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
hidden_size:
  desc: null
  value: 64
input_size:
  desc: null
  value: 1
num_classes:
  desc: null
  value: 3
